version: '3.8'
services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  flask-app:
    build:
      context: ./server
      dockerfile: Dockerfile   # your Flask app’s Dockerfile
    depends_on:
      - elasticsearch
    ports:
      - "5000:5000"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

volumes:
  esdata:
