name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: vue-extension/package-lock.json
        
    - name: Install dependencies
      run: |
        cd vue-extension
        npm ci
        
    - name: Run linter
      run: |
        cd vue-extension
        npm run lint 